name: Carnyx & Co.
markdown: redcarpet
redcarpet:
  extensions:
  - tables
highlighter: pygments
permalink: pretty
collections:
  projects:
    output: true
    permalink: /projects/:path/
  cds:
    output: true
    permalink: /cds/:path/
