name: Carnyx & Co.
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
highlighter: rouge
permalink: pretty
collections:
  projects:
    output: true
    permalink: /projects/:path/
  cds:
    output: true
    permalink: /cds/:path/
